language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp
  - git config --global user.name "Travis-CI"
  - git config --global user.email "jon@linesandwaves.com"
branches:
  only:
  - source
script: gulp travis
env:
  global:
  - GH_REF: github.com/jonlong/jonlong.github.io.git
  - secure: B7vul3Y+6eP81NxYJ32OqQb7GVcsf1FXNmXD7gceKCxWGixGe5cOAPshKV47CP4RF1wt6aHtu9Ny1gGeEyVS1nvO7io/xdTkMOlYsIYhC11I7RLkfYZ8W0PNZqfDCVyircHe70wUMLkHYSy7fXH036Z6J/k0RoWWe4QEPyEmKMQ=